[package]
name = "modulo"
version = "0.1.0"
authors = ["Felipe Saldanha <felipe.saldanha.souza@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
